"""Add Google OAuth fields

Revision ID: 40d7520514a1
Revises: c45e71ef924b
Create Date: 2025-09-17 16:07:15.858538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40d7520514a1'
down_revision: Union[str, Sequence[str], None] = 'c45e71ef924b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###
