"""Add module column to permissions

Revision ID: eb7131d79d4e
Revises: b74cb190f2d3
Create Date: 2025-09-15 12:29:32.578104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb7131d79d4e'
down_revision: Union[str, Sequence[str], None] = 'b74cb190f2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('module', sa.String(length=50), nullable=False, server_default='general'))
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_column('permissions', 'module')
    # ### end Alembic commands ###
